language: rust
cache: cargo
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - echo "Checking code formatting" ; cargo fmt --all -- --check
  - echo "Build project"  ; cargo build
  - echo "Run unit tests" ; cargo test
  - echo "Checking code lints" ; cargo clippy --tests -- -D clippy::all
